language: node_js
node_js:
- '4'
notifications:
  slack:
    rooms:
      secure: IcPY/tuHL3TaHLouWcMLOgvVWLAC2V0yh0GMj8wFrsUdPrVi7cf3rhvb3OIfP6850rrzFMUAkvsZMVKaWaP0Doo6YlFmUq9rtX1kFkNEb8B3uiFulGAkTAlERsm7fKrA8VRykYjbVq75Qn0eGaxKOByO3CCcPCdu/nRPYHzzA3F6Ot/1t5gGIAvu3GDxLCGOHmcYvX44nAdVg3t1rsHwQY45MIJS8D8JFV155o65mZD1D0zSIK9DHPExSGINJaqtJ8et/4KgVM0Jsz6NUpNhB1tY4wZ2fS5K5E/CCcCWnTvJtJCHBA56QF/gUkp4iHlxtOhwtWP5epUa9SeHa/mS8g/anETiqNKFJ72K1PqLJCAajikd83erMYHvfVrwqj8+KVvA8Kj46kXpTwGqVAh36QpJpYZVeHEIQIhMwfCjudZ3LUD4dGZ+pwVnCL9iIlfzz5qahMewG7qikQ8NOnvhzRKy5UsydwhItxTO+WUA0oBi+7E0yOtjhRQUv8u7cKtZmtHYAM4van2fLDdHk6xcwSmPBlJoswqyZ6VzKuapHPmOvzuIXWxiFbrun3xKx7wydrJB0p9TNr+7vA11STKcwoWfQicHoKvb1+53kn2DlQz/xG2MdNHm/tNCyX28t6l0RJpjaVPA3eTJmP0o0B/SUFjNNONnNhU9Iyh6xy5+dw8=
before_script:
- npm install -g gulp
script:
- gulp build:api
- gulp build:www
- gulp test
- gulp vet
